---
services:
  emby:
    image: emby/embyserver_arm64v8
    container_name: embyserver
    network_mode: host # Enable DLNA and Wake-on-Lan
    environment:
      - UID=1000
      - GID=1000
      - GIDLIST=1000
    volumes:
      - ./apps/emby/programdata:/config # Configuration directory
      - ./data/media:/library # Media directory
    ports:
      - 8096:8096 # HTTP port
      - 8920:8920 # HTTPS port
    devices:
      - /dev/dri:/dev/dri # VAAPI/NVDEC/NVENC render nodes
      - /dev/vchiq:/dev/vchiq # MMAL/OMX on Raspberry Pi
    restart: always

  # https://github.com/haugene/docker-transmission-openvpn
  transmission-openvpn:
    image: haugene/transmission-openvpn:latest
    container_name: transmission-openvpn
    restart: always
    ports:
      - "9091:9091"
      - '9117:9117'  # This is jackett Port – managed by VPN Service Network
    logging:
        driver: json-file
        options:
            max-size: 10m
    # https://haugene.github.io/docker-transmission-openvpn/provider-specific/#protonvpn
    environment:
      - OPENVPN_PROVIDER=custom
      - OPENVPN_CONFIG=au-353.protonvpn.udp
      - LOCAL_NETWORK=192.168.0.0/16
      - TRANSMISSION_WEB_UI=flood-for-transmission
      - TZ=Australia/Brisbane
    volumes:
      - ./protonvpn/:/etc/openvpn/custom/
      - ./data/downloads:/data
      - ./apps/transmission:/config
      - /etc/localtime:/etc/localtime:ro
    cap_add:
      - NET_ADMIN
    secrets:
      - openvpn_creds

  # https://github.com/linuxserver/docker-jackett
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
        - PUID=1000
        - PGID=1000
        - TZ=Australia/Brisbane
        - AUTO_UPDATE=true
    volumes:
        - ./apps/jackett:/config
    # You have to comment ports, they should be managed in transmission-openvpn section now.
#       ports:
#           - 9117:9117
    restart: always
    network_mode: "service:transmission-openvpn" # Add to the transmission-openvpn Container Network
    depends_on:
        - transmission-openvpn # Set dependency on transmission-openvpn Container
    healthcheck: # Here you will check if transmission is reachable from the Jackett container via localhost
        test: curl -f http://localhost:9091 || exit 1
        # Use this test if you protect your transmission with a username and password
        # comment the test above and un-comment the line below.
        #test: curl -f http://${TRANSMISSION_RPC_USERNAME}:${TRANSMISSION_RPC_PASSWORD}@localhost:9091 || exit 1
        interval: 5m00s
        timeout: 10s
        retries: 2

  # https://github.com/linuxserver/docker-radarr
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: always
    ports:
      - "7878:7878"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Australia/Brisbane
    volumes:
      - ./apps/radarr:/config
      - ./data/media/movies:/movies
      - ./data/downloads:/data/

  # https://github.com/linuxserver/docker-sonarr
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: always
    ports:
      - "8989:8989"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Australia/Brisbane
    volumes:
      - ./apps/sonarr:/config
      - ./data/media/tv:/tv
      - ./data/downloads:/data

  # https://github.com/dperson/samba
  samba:
    image: dperson/samba:latest
    container_name: samba
    restart: always
    # NOTE: see https://github.com/dperson/samba#troubleshooting
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - "139:139"
      - "445:445"
    environment:
      - USERID=1000
      - GROUPID=1000
      - SHARE=Media;/library
      - TZ=Australia/Brisbane
    volumes:
      - ./data:/library
secrets:
    openvpn_creds:
        file: ./openvpn_creds
